# Generated by Django 5.2.4 on 2025-07-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('swapped', 'Swapped'), ('sold', 'Sold')], default='available', max_length=20),
        ),
    ]
